import CPerlCore

/// A Perl execution environment.
///
/// You create and use Perl interpreters to evaluate Perl scripts from Swift code, to access values that Perl defines or calculates, and to make native objects accessible to Perl.
@available(macOS 10.10, *)
public class PerlInterpreter {
  var _perl: UnsafeMutableRawPointer!
  
  /// Initializes a new Perl interpreter.
  /// - returns: A new Perl interpreter.
  public init() {
    _perl = perlcore_init()
  }
  
  deinit {
    perlcore_deinit()
  }
  
  // TODO: find out why/when this is needed
  func reinit() {
    perlcore_deinit(); perlcore_init()
  }
  
  /// Initializes the Perl environment.
  public class func initialize() { perlcore_sys_init() }
  
  /// Deinitializes the Perl environment.
  public class func deinitialize() { perlcore_sys_term() }
  
  var preamble = "use v5.30; no strict;"
  
  /// Executes the specified Perl code.
  /// - parameters:
  ///   - script: The Perl source code to evaluate.
  /// - returns: The last value generated by the script. Note that a script can result in an undefined Perl value.
  ///
  /// Evaluating a script runs any top-level code and adds function and object definitions to the context’s global object.
  @discardableResult
  public func evaluateScript(_ script: String) -> PerlScalarValue {
    (preamble + script).withCString { PerlScalarValue(perlcore_eval_pv($0, 0)) }
  }
  
  /// Whether the latest evaluation succeeded.
  public var evaluationSucceeded: Bool {
    perlcore_err() == 0
  }
  
  /// A Perl exception thrown in evaluation of the script.
  ///
  /// PerlCore assigns any uncaught exception to this property, so you can check this property’s value to find uncaught exceptions arising from Perl function calls.
  public var exception: String {
    String(validatingUTF8: perlcore_errstr())!
  }
  
  /// Imports semantics from the specified Perl module.
  ///
  /// This imports some semantics into the current Perl package from the named Perl module, generally by aliasing certain subroutine or variable names into your Perl package.
  @discardableResult
  public func use(_ name: String) -> PerlScalarValue {
    evaluateScript("use \(name);")
  }
  
  /// Imports semantics from the specified Perl module.
  @discardableResult
  public func use<T>(_ name: String, _ args: T...) -> PerlScalarValue {
    use(name + " " + args.map{ "'\($0)'" }.joined(separator: ","))
  }
  
  /// Accesses the specified scalar value.
  public func `$`(_ name: String, _ add: Bool = false) -> PerlScalarValue? {
    scalarValue(name, add)
  }
  
  /// Accesses the specified scalar value.
  public func scalarValue(_ name: String, _ add: Bool = false) -> PerlScalarValue? {
    let value = name.withCString { perlcore_get_sv($0, add ? 1 : 0) }
    return value == nil ? nil : PerlScalarValue(value!)
  }
  
  /// Accesses the specified array value.
  public func arrayValue(_ name: String, _ add: Bool = false) -> PerlArrayValue? {
    let value = name.withCString { perlcore_get_av($0, add ? 1 : 0) }
    return value == nil ? nil : PerlArrayValue(value!)
  }
  
  /// Accesses the specified hash value.
  public func hashValue(_ name: String, _ add: Bool = false) -> PerlHashValue? {
    let value = name.withCString { perlcore_get_hv($0, add ? 1 : 0) }
    return value == nil ? nil : PerlHashValue(value!)
  }
}
